### ISSUE TITLE
FlakyBot is not detecting errors on the default branch

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/java-gcloud-maven-plugin#103]
So a little irony here.  I am looking at this PR:
https://github.com/googleapis/java-gcloud-maven-plugin/pull/102

What this tells me is that tests are likely failing on master, because my change is silly and all the other changes in this repo are failing.  That makes me think we don't have a nightly test with flakybot properly configured.

**Comment by danoscarmike** [comment]
@Neenu1995 could you take a look into this? @JustinBeckwith can point you to FlakyBot spec etc.

**Comment by danoscarmike** [comment]
@Neenu1995 here's FlakyBot: https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot#flakybot

@tbpg can also help with understanding

**Comment by Neenu1995** [comment]
This issue has been resolved in #106 .
